# Generated by Django 4.1.1 on 2023-09-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_quiz_answers_quiz_variants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='answers',
            field=models.JSONField(default={}),
        ),
    ]
